-- PyChronicle — SQLite schema
-- Dumped from pychronicle.db on 2026-07-29 23:11:22
-- Generated by tools/generate_docs.py — do not edit by hand.
--
-- Applying this file to an empty database produces the same structure
-- the tracer and the UI expect. Data is not included.

PRAGMA foreign_keys = ON;

-- ====================================================================
-- TABLES
-- ====================================================================

-- One row per statically parsed source file, produced by the AST module (`parser.py` + `visiter.py`).
CREATE TABLE ast_summary (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file TEXT UNIQUE,
    imports TEXT,
    variables TEXT,
    functions TEXT,
    classes TEXT,
    loops TEXT,
    conditions TEXT,
    returns TEXT,
    function_defs TEXT,
    class_defs TEXT,
    parsed_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- One row per trace step. This is the Trace Timeline.
CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event TEXT,
    function TEXT,
    file TEXT,
    line INTEGER,
    variables TEXT,
    timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
    session_id INTEGER,
    var_diff TEXT,
    FOREIGN KEY (session_id) REFERENCES sessions(id)
);

-- Bookkeeping for `tools/setup_db.py`: which legacy database files have already been merged, so merging is idempotent.
CREATE TABLE imported_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_path TEXT UNIQUE,
    events INTEGER,
    imported_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- One row per traced run. Groups events and drives the UI's session switcher.
CREATE TABLE sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    script_file TEXT,
    started_at TEXT,
    ended_at TEXT,
    total_events INTEGER DEFAULT 0,
    status TEXT DEFAULT 'running'
);

-- ====================================================================
-- INDEXES
-- ====================================================================

CREATE INDEX idx_events_event ON events (
    event
);

CREATE INDEX idx_events_file ON events (
    file
);

CREATE INDEX idx_events_function ON events (
    function
);

CREATE INDEX idx_events_line ON events (
    line
);

CREATE INDEX idx_events_session ON events (
    session_id
);

CREATE INDEX idx_events_session_id ON events (
    session_id, id
);

CREATE INDEX idx_events_timestamp ON events (
    timestamp
);

CREATE INDEX idx_sessions_started ON sessions (
    started_at
);
